env:
  browser: true
  es2021: true
  greasemonkey: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - 4
  linebreak-style: off
  no-restricted-globals: off
  no-underscore-dangle: off
globals:
  waitForElems: readonly
  waitForUrl: readonly
