env:
  browser: true
  es2021: true
  greasemonkey: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
rules:
  indent:
    - error
    - 4
  linebreak-style: [0]
  no-restricted-globals: [0]
  no-underscore-dangle: [0]
  radix: [0]
globals:
  waitForElems: readonly
  waitForUrl: readonly
